version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: 'Install python 3'
          command: |
            apt update
            apt install --yes python3 python3-pip python3-venv
      - run:
          name: 'Setup virtualenv'
          command: |
            mkdir -p ~/.virtualenvs
            python3 -m venv ~/.virtualenvs/target-stitch
            source ~/.virtualenvs/target-stitch/bin/activate
            pip install -U pip setuptools
            pip install -e .[dev]
      - run:
          name: 'Run tests'
          command: |
            # Need to re-activate the virtualenv
            source ~/.virtualenvs/target-stitch/bin/activate
            pylint target_kinesis
